remove Length usage and use Rent/Return for array pool.
abaza121/DotNetZip.Semverd-lowalloc pull request #1
Opened 2022-11-11 19:06 UTC by abaza121

2022-11-14 15:03 UTC, abaza121 commented on src/Zip.Shared/ZipEntry.Write.cs
> +            byte[] bytes = ArrayPool<byte>.Shared.Rent(BufferSize);
This could use span

2022-11-14 20:26 UTC, gzatravkin approved these changes

2022-11-15 05:01 UTC, mirasrael requested changes

2022-11-15 05:01 UTC, mirasrael commented on src/Zip.Shared/Shared.cs
> +                n = s.Read(buffer, offset, count);
why exception handling and retries removed? this loop then makes no sense because it either throw out or  done on first attempt

2022-11-15 05:01 UTC, mirasrael commented on src/Zip.Shared/ZipEntry.Write.cs
> +            Span<byte> bytes = stackalloc byte[BufferSize];
depending on buffersize and stack depth it may be a bad idea, because stack may overflow. As you said because of non-optimized Span version it may be better just use shared array as before here.

2022-11-15 05:01 UTC, mirasrael commented on src/Zlib.Shared/ArraySegmentUtils.cs
> +            Array.Copy(source.Array, source.Offset + sourceIndex, destination.Array, destination.Offset + destinationIndex, length);
can just do something like 
```csharp
source.Slice(sourceIndex, length).CopyTo(destination.Slice(destinationIndex, length))
```
also works with Array

2022-11-15 08:18 UTC, abaza121 commented on src/Zip.Shared/Shared.cs
> +                n = s.Read(buffer, offset, count);
IT seems to be meant for crash handling on cross platform (Permissions is removed from standard 2.1)

2022-11-15 08:20 UTC, abaza121 commented on src/Zip.Shared/Shared.cs
> -                        System.Security.Permissions.SecurityPermissionFlag.UnmanagedCode);
@mirasrael this class doesn't work but actually I havent tried looking into nuget I will check if I can revert that change but when I looked up is that it isn't recommended to use the SecurityPermission class

2022-11-15 08:50 UTC, abaza121 commented on src/Zlib.Shared/ArraySegmentUtils.cs
> +            Array.Copy(source.Array, source.Offset + sourceIndex, destination.Array, destination.Offset + destinationIndex, length);
didn't work for arrays for me and [0..len] would need calculation I created array segments for Array situations

2022-11-15 08:56 UTC, abaza121 commented on src/Zlib.Shared/ArraySegmentUtils.cs
> +            Array.Copy(source.Array, source.Offset + sourceIndex, destination.Array, destination.Offset + destinationIndex, length);
addressed but let me know what do you think of how it looks

2022-11-15 08:56 UTC, abaza121 commented on src/Zip.Shared/ZipEntry.Write.cs
> +            Span<byte> bytes = stackalloc byte[BufferSize];
addresed

2022-11-15 09:00 UTC, abaza121 commented on src/Zip.Shared/Shared.cs
> +                n = s.Read(buffer, offset, count);
yup turns out I just needed to grab it from nuget, addressed.

2022-11-15 10:24 UTC, mirasrael approved these changes

2022-11-15 10:28 UTC, merged